### ISSUE TITLE
The command creating the cluster never ends when we run: "idpbuilder create --package-dir ./pkg/controllers/custompackage/test/resources/customPackages/testDir"

### ISSUE THREAD

**Issue by cmoulliard** [cnoe-io/idpbuilder#107]
### What is your environment, configuration, and command?

The command creating the cluster never ends when we run the command `idpbuilder create --package-dir ./pkg/controllers/custompackage/test/resources/customPackages/testDir` and to exit it is needed to use `ctrl-c`. Is it a normal behaviour ?

```
1.7023726693576362e+09  INFO    controller.localbuild   Gitea is ready! {"reconciler group": "idpbuilder.cnoe.io", "reconciler kind": "Localbuild", "name": "localdev", "namespace": ""}
1.702372669357645e+09   INFO    controller.localbuild   installing bootstrap apps to ArgoCD     {"reconciler group": "idpbuilder.cnoe.io", "reconciler kind": "Localbuild", "name": "localdev", "namespace": ""}
1.702372669357651e+09   INFO    controller.localbuild   Ensuring embedded ArgoCD Application    {"reconciler group": "idpbuilder.cnoe.io", "reconciler kind": "Localbuild", "name": "localdev", "namespace": "", "name": "argocd"}
1.702372669377444e+09   INFO    controller.localbuild   Ensuring embedded ArgoCD Application    {"reconciler group": "idpbuilder.cnoe.io", "reconciler kind": "Localbuild", "name": "localdev", "namespace": "", "name": "nginx"}
1.702372669386388e+09   INFO    controller.localbuild   Ensuring embedded ArgoCD Application    {"reconciler group": "idpbuilder.cnoe.io", "reconciler kind": "Localbuild", "name": "localdev", "namespace": "", "name": "gitea"}
1.702372669392459e+09   INFO    controller.localbuild   Ensuring embedded ArgoCD Application    {"reconciler group": "idpbuilder.cnoe.io", "reconciler kind": "Localbuild", "name": "localdev", "namespace": "", "name": "backstage"}
1.702372669397901e+09   INFO    controller.localbuild   Ensuring embedded ArgoCD Application    {"reconciler group": "idpbuilder.cnoe.io", "reconciler kind": "Localbuild", "name": "localdev", "namespace": "", "name": "crossplane"}
1.702372669404875e+09   INFO    controller.localbuild   Checking if we should shutdown  {"reconciler group": "idpbuilder.cnoe.io", "reconciler kind": "Localbuild", "name": "localdev", "namespace": ""}
1.7023726800948448e+09  INFO    controller.custompackage        reconciling custom package      {"reconciler group": "idpbuilder.cnoe.io", "reconciler kind": "CustomPackage", "name": "app-my-app", "namespace": "idpbuilder-localdev", "name": "app-my-app", "namespace": "idpbuilder-localdev"}
1.702372680108734e+09   DEBUG   events  Normal  {"object": {"kind":"CustomPackage","namespace":"idpbuilder-localdev","name":"app-my-app","uid":"29ce4a22-129b-45fc-8d9a-17606da9a02d","apiVersion":"idpbuilder.cnoe.io/v1alpha1","resourceVersion":"1092"}, "reason": "reconcile success", "message": "Successfully reconciled"}
1.7023726846419258e+09  INFO    controller.gitrepository        reconciling GitRepository       {"reconciler group": "idpbuilder.cnoe.io", "reconciler kind": "GitRepository", "name": "my-app-busybox", "namespace": "idpbuilder-localdev", "name": "my-app-busybox", "namespace": "idpbuilder-localdev"}
1.7023726846420748e+09  INFO    controller.gitrepository        reconciling     {"reconciler group": "idpbuilder.cnoe.io", "reconciler kind": "GitRepository", "name": "my-app-busybox", "namespace": "idpbuilder-localdev", "name": "my-app-busybox", "dir": {"path":"/Users/cmoullia/code/cnoe/fork-idpbuilder/pkg/controllers/custompackage/test/resources/customPackages/testDir/busybox","type":"local"}}
1.7023726847186098e+09  DEBUG   events  Normal  {"object": {"kind":"GitRepository","namespace":"idpbuilder-localdev","name":"my-app-busybox","uid":"6ee1c23a-2c21-4eb3-9f18-a67871329279","apiVersion":"idpbuilder.cnoe.io/v1alpha1","resourceVersion":"1114"}, "reason": "reconcile success", "message": "Successfully reconciled"}
```

### What did you do and What did you see instead?

git clone the project
make
./idpbuilder create --package-dir ./pkg/controllers/custompackage/test/resources/customPackages/testDir

### Additional Information. Logs.

```shell
N/A
```

**Comment by nabuskey** [comment]
This is an intended bahaviour introduced with the custom package flag. Reasoning being that when you specify a directory,  I wanted the controller to continuously sync the contents of the directory to the git repository. But I do see use cases where this may not be the desirable behaviour. Perhaps we should consider adding an additional flag that controls if the CLI should exit regarldess of other flags.

**Comment by cmoulliard** [comment]
> Reasoning being that when you specify a directory, I wanted the controller to continuously sync the contents of the directory to the git repository

This is not a bad practice that the controller waits but then we should add a message like `Controller is currently deploying ArgoCD resources. To exit please do: ctrl-c"

**Remark**: As ArgoCD will deploy the resources, then that should be great if the controller could every 5-10s shows the status of the sync. If we do that then the users will be aware about what it happens: good or bad and will be very happy to use idpbuilder ;-)

@nabuskey

**Comment by blakeromano** [comment]
I think this goes back to a question of like "What mode do you want to run it in?". In my head there's a couple modes that are possible for right now:

1. Reconcile for life mode - Where CNOE CLI always is running and never stops until exits and while validate any changes made are reconciled with what is actually deploy.
2. Get me up - Where CNOE CLI runs just to get everything into a desired state and exits once done. This would make it so any changes to directory done locally would not be reflected unless command was rerun.


I do wonder if eventually instead of needing CNOE CLI to run forever if we made it so custom package additions/removals updated the KIND Config to mount the directory https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts and had CNOE run as an operator if we could get away with CNOE being able to reconcile local changes that way....

**Comment by cmoulliard** [comment]
To avoid to develop a too complex client (aka idpbuilder), we should keep the design of the solution as smart as possible. As the purpose of the tool (until now) and command `idpbuilder create` is to create a kind cluster and install ingress + gitea + argocd then the process should exit when they are healthy. 

As the parameter `--package-dir` allows to pass Applications CR to ArgoCD, then this is the job of ArgoCD to sync the resources and by consequence, the user should then look using argoCD CLI or UI if the additional packages have been well deployed.

Nevertheless, end of the process to install/sync the core components resources, then a more human readable message should be displayed and explaining to the user what they should do. I'm much more in favour to exit like it happens when you use: kind, minikube even if pods are not yet running.

**Comment by nimakaviani** [comment]
yeah +1 from me on @cmoulliard 's suggestion.

the goal of the idpbuilder CLI should be to bootstrap. it shouldn't break the promise of regular GitOps best practices. That is to say, git should continue to be the source of truth.

Right now, it appears that for custom packages, the source of truth becomes the local directory, and this breaks the GitOps contract. 

I very much like the idea for the idpbuilder to just bootstrap the behavior and exit. if you need to make changes to your local directory stuff, OR to add new local custom packages, you run the idpBuilder cli again with updated list of package directories, etc. for existing packaegs, a re-run could override the content of the correspnding GitRepos and that is ok, since it was asked to.

**Comment by nabuskey** [comment]
> I do wonder if eventually instead of needing CNOE CLI to run forever if we made it so custom package additions/removals updated the KIND Config to mount the directory https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts and had CNOE run as an operator if we could get away with CNOE being able to reconcile local changes that way....

This was what I thought of before as well, but I was not sure of implications associated with this. What happens if we want to run multiple instances?  Are there performance implications when multiple deeply nested and subnested directories are mounted? Do they work for non-docker providers? I didn't have answers for them. So I went with the simplest solution BUT we can definitely re-visit. 

> I very much like the idea for the idpbuilder to just bootstrap the behavior and exit. if you need to make changes to your local directory stuff, OR to add new local custom packages, you run the idpBuilder cli again with updated list of package directories, etc. for existing packaegs, a re-run could override the content of the correspnding GitRepos and that is ok, since it was asked to.

Yeah I am inclined to revert it so that the default behaviour of CLI  is to exit as soon as bootstrapping finishes. We can provide an optional flag to not exit.

**Comment by cmoulliard** [comment]
> Yeah I am inclined to revert it so that the default behaviour of CLI is to exit as soon as bootstrapping finishes. We can provide an optional flag to not exit.

+1

**Comment by cmoulliard** [comment]
> I think this is not a bad thing for local development purposes. I personally hate having to push every single change to a repo when trying to get things working. But I agree otherwise, the core purpose of idpbuilder should be to bootstrap a ready to use cluster with whatever you want.

The compromise could be to push to the Gitea server the ArgoCD CR and resources (= what is defined under a package-dir). As the purpose of IDPBuilder is also to provision the cluster with packages A, B, C needed for backstage components X, Y, Z , then it will be needed that the users know how to describe what their IDP should be (= package A, B, C etc) and how to provision the cluster using our idpbuilder ...

**Comment by jessesanford** [comment]
> I think this is not a bad thing for local development purposes. I personally hate having to push every single change to a repo when trying to get things working. But I agree otherwise, the core purpose of idpbuilder should be to bootstrap a ready to use cluster with whatever you want.

What if we had a second command that could be run that could sync to gitea. I think that separating out that functionality would be appropriate. We could even have a flag that would output the gitea git remote urls for the packages on stdout so that they could be automatically passed in to a script designed to automatically sync commits from local working copies to remotes. There are possibly hundreds of these out on the internet: https://github.com/GitJournal/git-auto-sync

for example:

```idpbuilder create --package-dir ./pkg/controllers/custompackage/test/resources/customPackages/testDir --output-git-remote-urls | git-auto-sync ./pkg/controllers/custompackage/test/resources/customPackages/testDir```

**Comment by nimakaviani** [comment]
+1 on @nabuskey 's suggestion about separating this out into its own issue. I created #123 to track this.
