### ISSUE TITLE
move Crossplane and Backstage out of core embedded packages

### ISSUE THREAD

**Issue by nimakaviani** [cnoe-io/idpbuilder#119]
Given that the feature to install custom packages is delivered, there is little value to embed other components outside of the core components (ie Argo CD and Gitea) into the idpbuilder binary.

Following the slack conversation [here](https://cloud-native.slack.com/archives/C05TN9WFN5S/p1702488976000879?thread_ts=1702364239.785349&cid=C05TN9WFN5S) it appears that the general consensus is to pull both out and make them available as installable custom packages.

For this to happen, and with the removal of the `gitserver`, we can move the directories for Backstage and Crossplane from `pkg/apps/srv` to  `pkg/apps` and remove the controller logic that deploys them as embedded apps.

For those running the idpbuilder, if they run from source, they can always include the included custom packages for crossplane and backstage by referring to them using the `--package-dir`flag to receive the minted CNOE versions, or they can have their own Argo app configurations to pull these installations from remote sources.

**Comment by nabuskey** [comment]
I am inclined to remove them. But from naming standpoint, `idpbuilder` kinda loses its meaning because we now don't have an out of the box experience that comes with the binary. It reduced its scope to just setting up GitOps environment.

**Comment by cmoulliard** [comment]
This is not because you will remove from the embedded = core packages backstage that it should not be installed and it should as the purpose of our idp cli is to onboard it ! 

What I mean is that it should be installed using the GitOps way with the help of our ArgoCD & Git Servers.

Here is the scenario that I'm proposing:
- Based on a list of `Package/Capability: cnoe-backstage, certificate-manger, etc` to be installed (see my excalidraw file [here](https://github.com/cnoe-io/website/pull/32)), the platform will read the content definition, will translate the Package/Capability definition into the needed CR: ArgoCD, Git, etc
- A Git repo is created and content pushed to the internal git repo under version x.y.z
- Next, ArgoCD will sync the resources and install such defined PAckage/Capability (backstage, crossplane, cert manager, vault, etc)
- If the Package definiion includes tasks to be executed, then the corresponding Task(run)s will be generated and deployed to customize the package installed. The platform should support different workflow engines and been able to translate the task defintion into the corresponding CR: Tekton, Argo Workflow, etc
