### ISSUE TITLE
Restructure gitserver and idpbuilder to allow for pluggable images of argo apps

### ISSUE THREAD

**Issue by jessesanford** [cnoe-io/idpbuilder#4]
Create a GitServerImageUrl field on the localbuild resource so users can pass in a prebuilt gitserverimage. Also create a ImageUrl field on the gitserver resource so we can set it below. If gitserverimage is set on this localbuildresource, just pass it through to the gitserver resource via it's gitserverimageurl in the spec below. If gitserverimage is not set on this resource we should assume that folks want us to create an image with the default embedded argo apps so we should build the image here and then pass in the url via the gitserverimageurl field in the spec below. We can move the image.go file from the gitserver controller folder to this folder and reuse that logic.

https://github.com/cnoe-io/idpbuilder/blob/4d2048155151a98c9f13472d7f9cbb6ae6483298/pkg/controllers/localbuild/controller.go#L140-L145

**Comment by cmoulliard** [comment]
Why do you install a git server using a project forked 6 years ago https://github.com/cirocosta/gitserver-http/ instead of a project which is maintained as gitea and that we could install/configure more easily as described here using a helm chart: https://inlets.dev/blog/2023/01/27/self-hosting-gitea-kubernetes.html ?

**Comment by jessesanford** [comment]
Closing this in favor of a full RFC on packaging See: #5
