### ISSUE TITLE
idpbuilder in codespaces needs https not http

### ISSUE THREAD

**Issue by agardnerIT** [cnoe-io/idpbuilder#452]
Spinning up idpbuilder following hte codespaces instructinos, I see:

```
Can Access ArgoCD at http://literate-space-halibut-96wwg755xv7hxp7g-8080.app.github.dev:8080/argocd
```

I believe the URL is build on [this line](https://github.com/cnoe-io/idpbuilder/blob/8c6cd9704ae118981a89b3c5b541db1924f31643/pkg/cmd/create/root.go#L172) and indeed the docs instructions do specify `--protocol http`

However, GitHub really does want an `https://` URL.

So...

1. Should the docs be updated to read `--protocol https`
2. Does the code need a special condition if Github codespaces then protocol is https?

**Comment by nabuskey** [comment]
Hey @agardnerIT,

Thanks for reporting this issue. In Codespaces or other environments where a proxy is involved in front of idpbuilder, the ArgoCD URL given at the end is inaccurate. See this issue: https://github.com/cnoe-io/idpbuilder/issues/269

The `--protocol http` is needed for Codespaces to proxy requests correctly. Otherwise, you have two TLS certs involved when making requests from your laptop. 

This isn't just an issue with protocol either btw. The port number printed is incorrect as well. e.g. `443` vs `8080`. The expectation we have from users is to access it using the port forward popup you get in Codespaces, not the URL given by idpbuilder. 

Having said that, we do need to fix this.
